image: node:lts

before_script:  
  - apt-get update -qq && apt-get install
  # - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY") > /dev/null 2>&1
  - mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\tLogLevel=quiet\n\n" > ~/.ssh/config
  # - npm -g install yarn

cache:
  paths:
    - node_modules/
    - .yarn

stages:
#  - build
  - deploy
  
#build:
#  stage: build
#  before_script: 
#    - yarn config set cache-folder .yarn
#  script:
#    - yarn build
#    - ssh -v ubuntu@3.22.62.199

deploy:
  stage: deploy
  script:
    - ssh -v ubuntu@3.22.62.199
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./** ubuntu@3.22.62.199:/path/
