image: node:lts

before_script:  
  - apt-get update -qq && apt-get install
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
#  - npm -g install yarn

#cache:
#  paths:
#    - node_modules/
#    - .yarn

stages:
  - build
  - deploy
  
build:
  stage: build
  #before_script: 
  #  - yarn config set cache-folder .yarn
  script:
    - ls
    - ssh -v ubuntu@$HOST
deploy:
  stage: deploy
  script:
    - ssh -v ubuntu@$HOST