image: node:lts

before_script:  
  - apt-get update -qq && apt-get install
  - apt install -y rsync
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - cat "$TEST" | tr -d '\r' | ssh-add -

cache:
  paths:
    - node_modules/
    - .yarn

stages:
#  - build
  - deploy

#build development:
#  stage: build
#  only:
#    - dev
#  script:
#    - yarn

deploy master:
  stage: deploy
  only:
    - master
    - merge_requests
  script:
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./** gitlab@100.69.4.76:/var/storage/apps/bodhisys/apps-dev/bohdisys-api
    - ssh -o StrictHostKeyChecking=no ubuntu@100.69.4.76 "cd /var/storage/apps/bodhisys/apps-dev/bohdisys-api; yarn; pm2 restart bodhisys-api"


deploy development:
  stage: deploy
  only:
    - dev
    - merge_requests
  script:
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./** gitlab@100.69.4.76:/var/storage/apps/bodhisys/apps-dev/bohdisys-api
    - ssh -o StrictHostKeyChecking=no gitlab@100.69.4.76 "cd /var/storage/apps/bodhisys/apps-dev/bohdisys-api; yarn; pm2 restart bodhisys-dev-api"


